sudo: false
cache: pip

language: python

python:
    - 3.6
    - 2.7

install:
    - pip install tox

script:
    - tox

deploy:
    - provider: pypi
      user: cthoyt
      password:
          secure: WK8SA0Vtdn9a4RMdpn8L0CFbHs/3a+mOJrwYLaL4kzzZNWjL3yt0ygnhY5138pQoy5ygQ/bLT/COJIE9cN0qP0uUyBMgerUPWozkXryoz79zsQxe2HXHkG/XMhxuNjvPwRKjw9+tmz/wWoCeMFQ0JczNvOg2DYFcT4ruqLY5muHBuMErVB5pwjGSpYmDAEpI30x6KEJTXz5VIDxRpLhI6uehpItBW195Yj5GRAWllnGTqn9zRTeZR7SME1/p2Af1RVOlam4Ur/3hSXYDMUqErNj/vrxvxgpO9lDakfpSUV0U7pETgwQ+g8mp0fgm8I643jfu4Zoj8lITf9ewl9CteiaC80gV4Nj9JA9mdGiiaZwmpkEPUiMq6YLaqef6QDJEL2kx1q40+cOOsnTWe3PjnmRx9oAovQR9koqz1kztr3F++D3H65s6Y+LF46mmAlQs5mQ2sjGGGzd8agBcmoBzAG/Y/oTpkLbZ1Xq1qMSTQML7b0AHgbkWsy0QYUm56pX35uMrcl+r5BezJ5dAG+p3FDfEurD9iR9I0pUoWcE3zZldA1EFNsX6tnrLUwXGrAX7YGT7ul9DgHnD/h8hsS2qcrktTgzWIBIEZSpXiWUoM7Wy0TMbBq+iU+83lhCfQqnOb8fiMaH09v2neMmmsaazIIdF9JIMS9Caq5x7Q/iujeI=
      distributions: "sdist bdist_wheel"
      on:
          tags: true
          repo: cthoyt/ols-client
          branch: master
    - provider: pypi
      user: choyt
      server: https://arty.scai.fraunhofer.de/artifactory/api/pypi/pypi/simple
      password:
          secure: f77gDL4AbAqFDgf83sZLgYyMlinwFYoRJ32oggTGush4zHxUGV8q2c/gpB3+pQWVUAN9JV6wKWSWbx7mc8/zpSvJ3MCBWSZRf0jpfxwUPOQEvj3o+fWPDjoSW5RGQUdrrdmAXfpO9J1dQxNu47TpEApdnnWr2enaXe/HXZ0maGLpCugt0LltVvvnL1F/39J0J+jvNcAd9497ykq/rdE6KMYhQ9SO/jjDRd9IP+7cAov+AVFmU5P0+KzPzOghAy8I9SQZfAmtUIEGr7H0SJhNviAjc8oSqc4Nr9Yofc1nen4olduu52sNjPkn8oqHAfzm8YBHh5ZXjpLOHX3au01XOmwo/htyD8dN+8pDJ7TZ7M7SmMUY6lmlBdb+ToVHFeMoV3U7n5v6skKRCjnGy/VNqqIKhhh7uDrDRpmjMkSePhH0glFvrIlOGwqR2wWaCv0zmpPlDKZ7Szjub6SBpzC8oicnZ1Uhg3sma9xAw2vtI769yrwCKHxvBH37FAjm/j2OVZ44OdvERmToHCMutxECZ2Pb2pd4lltD7Sq145XcRnKvriPWJD/aUM+ML3kXNcmRDVmttWmPfFm66LMCjbTeBlyda7q5cXfnYiK/59DOLudbptXQXFfASxdjhOvM4OulGzYQxdGlgNM4j5figcU3IJ9Az+d+pgfv6ISLT2fbDqE=
      distributions: "sdist bdist_wheel"
      on:
          tags: true
          repo: cthoyt/ols-client
          branch: master
