sudo: false
cache: pip

language: python

python:
    - 3.6
    - 3.5
    - 3.4
    - 2.7

env:
  matrix:
    - TOXENV=py

matrix:
    include:
        - python: 3.6
          env: TOXENV=docs
        - python: 3.6
          env: TOXENV=manifest
        - python: 3.6
          env: TOXENV=rst-lint

before_install:
    - pip install codecov

install:
    - pip install tox

script:
    - tox

after_success:
    - tox -e coverage-report
    - codecov

deploy:
    - provider: pypi
      user: cthoyt
      password:
          secure: NXiH4m4dj6NkB+vLvFeUzcXI1HRwT66r6Ke7qTy8TBTZmD5lc0I4PELhuz7YzdJitbL7iPSibQ1rpbGe2hc25zq+NBmPNJE4BMswVmxLQeWv/TINvqPAllrgpGJAQC0COoj/qkI5yj3FI+k35GGLaMMTw8fWWAKhUXIH/C0QPpSdcIFjJgKeXAhyoZQafIaubTAtU1lLe7+Bu2/le0J2Ww8AqiB9PMnVgnj/RcxPnukM5o+0rZ9YKPkOC0DrPyZpfQAOWUVeC73vTc13vxQahFVjytrfEEsBlTNdQ7myaWXaSsZ2ZDWjPSbY1Qwwri3k+lZdNTQnqepaxniil+f3DgvTYNMwtmcetu/UglW58d/y+yyY2TrZ7SRPyaWPElE7kP8j5QUpr2eklIH2+8VJhSA6d1CeN8lwSuo3DC3OO2uKctyH4xQI5V8cD7Ds0OsVaacTabwkVjF3WCnhslDqvFuRVqwUEiLU8cwocO4gbrW1HFvQuMA7fgUIASHUBy69nXzb+pvTSVBpPN+ixZjB9eZFsmMkqTw+TxMO416qXrK3nX8mqdInkmXRNQrvOY9vBPsykMc0zkMQJ54vbFJB1lbvcS51OGHw97uGi06EBdFcNNebVBvp2SJy3Xwnmr/UommXc2HU1WlJDIFzWRW6mSYjBCnaiC98fFVmM885G+8=
      distributions: "sdist bdist_wheel"
      on:
          tags: true
          repo: cthoyt/ols-client
          branch: master
    - provider: pypi
      user: choyt
      server: https://arty.scai.fraunhofer.de/artifactory/api/pypi/pypi/simple
      password:
          secure: f77gDL4AbAqFDgf83sZLgYyMlinwFYoRJ32oggTGush4zHxUGV8q2c/gpB3+pQWVUAN9JV6wKWSWbx7mc8/zpSvJ3MCBWSZRf0jpfxwUPOQEvj3o+fWPDjoSW5RGQUdrrdmAXfpO9J1dQxNu47TpEApdnnWr2enaXe/HXZ0maGLpCugt0LltVvvnL1F/39J0J+jvNcAd9497ykq/rdE6KMYhQ9SO/jjDRd9IP+7cAov+AVFmU5P0+KzPzOghAy8I9SQZfAmtUIEGr7H0SJhNviAjc8oSqc4Nr9Yofc1nen4olduu52sNjPkn8oqHAfzm8YBHh5ZXjpLOHX3au01XOmwo/htyD8dN+8pDJ7TZ7M7SmMUY6lmlBdb+ToVHFeMoV3U7n5v6skKRCjnGy/VNqqIKhhh7uDrDRpmjMkSePhH0glFvrIlOGwqR2wWaCv0zmpPlDKZ7Szjub6SBpzC8oicnZ1Uhg3sma9xAw2vtI769yrwCKHxvBH37FAjm/j2OVZ44OdvERmToHCMutxECZ2Pb2pd4lltD7Sq145XcRnKvriPWJD/aUM+ML3kXNcmRDVmttWmPfFm66LMCjbTeBlyda7q5cXfnYiK/59DOLudbptXQXFfASxdjhOvM4OulGzYQxdGlgNM4j5figcU3IJ9Az+d+pgfv6ISLT2fbDqE=
      distributions: "sdist"
      on:
          tags: true
          repo: cthoyt/ols-client
          branch: master
